services:
  neunet:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - dataset:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: tail -F anything
  neunet_cpu:
    build:
      context: .
      dockerfile: DockerfileCPU
    volumes:
      - dataset:/data
    command: tail -F anything

volumes:
  dataset:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./how2sign
