services:
  neunet:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./how2sign:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: tail -F anything
  neunet_cpu:
    build:
      context: .
      dockerfile: DockerfileCPU
    volumes:
      - ./how2sign:/data
    command: tail -F anything
